spring:
  application:
    name: database
  profiles:
    active: default
  cloud:
    config:
      enabled: true
server:
  port: 8001
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discoveryserver:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/