server:
  port: 9090
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    service-gateway:
      serviceId: database
    database: /database/**
    servicecrud: /servicecrud/**
    teacher-service: /teacher-service/**

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      authorized-grant-types: authorization_code, refresh_token, password
      scope: openid
