spring:
  application:
    name: servicehongfah
  profiles:
    active: default
  cloud:
    config:
      enabled: true
server:
  port: 8009
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discoveryserver:8761/eureka/
